<?php
if($block->canShowDevTool()):
 if ($detailedInfoGroup = $block->getGroupChildNames('devtool', 'getChildHtml')):?>
    <div class="product info detailed">
        <?php $layout = $block->getLayout(); ?>
        <div class="product data items" data-mage-init='{"tabs":{"openedState":"active"}}'>
            <?php foreach ($detailedInfoGroup as $name):?>
                <?php
                    $html = $layout->renderElement($name);
                    if (!trim($html)) {
                        continue;
                    }
                    $alias = $layout->getElementAlias($name);
                    $label = $block->getChildData($alias, 'title');
                ?>
                <div class="data item title"
                     aria-labeledby="tab-label-<?php echo $alias;?>-title"
                     data-role="collapsible" id="tab-label-<?php echo $alias;?>">
                    <a class="data switch"
                       tabindex="-1"
                       data-toggle="switch"
                       href="#<?php echo $alias; ?>"
                       id="tab-label-<?php echo $alias;?>-title">
                        <?php echo $label; ?>
                    </a>
                </div>
                <div class="data item content" id="<?php echo $alias; ?>" data-role="content">
                    <?php echo $html; ?>
                </div>
            <?php endforeach;?>
        </div>
    </div>
<?php endif;
endif;
 ?>
